In [ ]:
# This file contains functions that alternate the points on the graph to add noise to the training sets.

In [51]:
import igl
import torch.optim as optim
import torch
import numpy as np
from numpy.random import default_rng
import linecache
%run NNs.ipynb
%run helpers_preproc.ipynb

In [131]:
mkdir = 'SHREC11_copy/'

In [156]:

def alternate_obj(fName, radius):
    v, f = igl.read_triangle_mesh(mkdir + fName)
    print(v)
    v = v + np.random.random(v.shape) *radius
    return v, f


In [157]:
alternate_obj("T0.obj", 0.0005)

[[ 6.874330e-01 -4.996540e-01  9.124600e-02]
 [ 6.833810e-01 -5.277220e-01  2.660700e-02]
 [ 6.351100e-01 -4.278610e-01  9.106900e-02]
 [ 6.649180e-01 -3.719120e-01  8.628200e-02]
 [ 6.885540e-01 -4.804060e-01  3.222400e-02]
 [ 6.799420e-01 -4.324770e-01  9.182900e-02]
 [ 6.261400e-01 -4.941260e-01  5.718100e-02]
 [ 6.712060e-01 -3.221700e-01  2.056400e-02]
 [ 6.436750e-01 -3.852510e-01  3.151300e-02]
 [ 6.395650e-01 -3.170770e-01  3.646600e-02]
 [ 6.633100e-01 -5.418150e-01  1.228700e-02]
 [ 5.612550e-01 -4.661140e-01 -1.125900e-02]
 [ 5.684050e-01 -4.283470e-01  2.772200e-02]
 [ 6.061490e-01 -3.724520e-01  4.953200e-02]
 [ 6.643420e-01 -1.998340e-01  3.517400e-02]
 [ 6.625190e-01 -1.029370e-01  4.068400e-02]
 [ 6.902960e-01 -2.086940e-01  3.211700e-02]
 [ 6.949830e-01 -5.751250e-01 -4.283500e-02]
 [ 6.169550e-01 -4.909500e-02  3.397800e-02]
 [ 6.918150e-01 -5.222310e-01 -3.139100e-02]
 [ 6.783340e-01 -2.174010e-01 -8.735000e-03]
 [ 6.246950e-01 -1.652260e-01 -7.316000e-03]
 [ 7.13704

(array([[ 6.87726120e-01, -4.99530377e-01,  9.15507655e-02],
        [ 6.83827687e-01, -5.27407775e-01,  2.70210144e-02],
        [ 6.35211526e-01, -4.27654111e-01,  9.12750001e-02],
        [ 6.65373151e-01, -3.71425898e-01,  8.63200142e-02],
        [ 6.88759061e-01, -4.80071206e-01,  3.23822231e-02],
        [ 6.79980349e-01, -4.32095805e-01,  9.18510772e-02],
        [ 6.26484902e-01, -4.93885190e-01,  5.76389285e-02],
        [ 6.71591432e-01, -3.22125467e-01,  2.10020859e-02],
        [ 6.44097166e-01, -3.84903754e-01,  3.18171621e-02],
        [ 6.39895589e-01, -3.17018445e-01,  3.68583300e-02],
        [ 6.63403058e-01, -5.41526835e-01,  1.23974252e-02],
        [ 5.61391738e-01, -4.65671600e-01, -1.09449017e-02],
        [ 5.68635125e-01, -4.27914176e-01,  2.80151798e-02],
        [ 6.06443652e-01, -3.72390007e-01,  5.00022979e-02],
        [ 6.64710297e-01, -1.99754858e-01,  3.55218755e-02],
        [ 6.62880774e-01, -1.02545502e-01,  4.06970307e-02],
        [ 6.90698367e-01