In [16]:
# This file contains functions that alternate the points on the graph to add noise to the training sets.

In [36]:
import igl
import numpy as np
from numpy.random import default_rng


In [37]:
mkdir = 'SHREC11_copy/'

In [48]:

def alternate_obj(fName, radius):
    v, f = igl.read_triangle_mesh(fName)
    v = v + np.random.random(v.shape) *radius
    return v, f

def write_new_files(origin_name,new_name,radius):
    v,f = alternate_obj(origin_name,radius)
    file = open(new_name, "w")
    return igl.write_obj(new_name, v, f)

def readLbl(fileName):
    #takes in file name, returns the labels as an array
    file1 = open(fileName, 'r')
    Lines = file1.readlines()
    count = 0
    lbls = np.empty([600])
    # Strips the newline character
    for line in Lines:
        count += 1
        text = line.strip()[1:].split('.')
        text[1] = text[1].split(' ')[1]
        lbls[int(text[0])] = int(text[1])
        #print("Line{}: {}".format(count, )))
    return lbls

def update_label():
    label_np = np.array(readLbl('SHREC11_copy/labels_copy.txt'))
    file = open(mkdir + "labels_copy.txt", "a")
    for i in range (600):
        file.write("T" + str(i + 600) + ".obj" + " " + str(label_np[i]) + "\n")

    return file


In [49]:
# label_np = np.array(readLbl(mkdir+'labels_copy.txt'))
# file = open(mkdir + "labels_copy.txt", "a")
# print(label_np[0])
# file.write("T600.obj"+ " " + str(label_np[0])+ "\n")

In [50]:
for i in range(600):
    origN = mkdir + 'T' + str(i) + '.obj'
    newN = mkdir + 'T' + str(i+600) + '.obj'
    print(write_new_files(origN,newN,0.008))

update_label()

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


<_io.TextIOWrapper name='SHREC11_copy/labels_copy.txt' mode='a' encoding='UTF-8'>

[[ 6.874330e-01 -4.996540e-01  9.124600e-02]
 [ 6.833810e-01 -5.277220e-01  2.660700e-02]
 [ 6.351100e-01 -4.278610e-01  9.106900e-02]
 [ 6.649180e-01 -3.719120e-01  8.628200e-02]
 [ 6.885540e-01 -4.804060e-01  3.222400e-02]
 [ 6.799420e-01 -4.324770e-01  9.182900e-02]
 [ 6.261400e-01 -4.941260e-01  5.718100e-02]
 [ 6.712060e-01 -3.221700e-01  2.056400e-02]
 [ 6.436750e-01 -3.852510e-01  3.151300e-02]
 [ 6.395650e-01 -3.170770e-01  3.646600e-02]
 [ 6.633100e-01 -5.418150e-01  1.228700e-02]
 [ 5.612550e-01 -4.661140e-01 -1.125900e-02]
 [ 5.684050e-01 -4.283470e-01  2.772200e-02]
 [ 6.061490e-01 -3.724520e-01  4.953200e-02]
 [ 6.643420e-01 -1.998340e-01  3.517400e-02]
 [ 6.625190e-01 -1.029370e-01  4.068400e-02]
 [ 6.902960e-01 -2.086940e-01  3.211700e-02]
 [ 6.949830e-01 -5.751250e-01 -4.283500e-02]
 [ 6.169550e-01 -4.909500e-02  3.397800e-02]
 [ 6.918150e-01 -5.222310e-01 -3.139100e-02]
 [ 6.783340e-01 -2.174010e-01 -8.735000e-03]
 [ 6.246950e-01 -1.652260e-01 -7.316000e-03]
 [ 7.13704